# Order: <model name>, default, dataset
# Code: https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/978eb7f1ccb994f580f9c74309321ad1cf2a5d7e/lmms_eval/api/task.py#L790
# NOTE: DO NOT change the keys in the model fields, as they are used in medvision_utils.py
# Caveat: DO NOT remove empty model fields
lmms_eval_specific_kwargs:
  healthgpt_l14:
    model: "healthgpt_l14"
    base_model_hf: "microsoft/phi-4"
    vision_model_hf: "openai/clip-vit-large-patch14-336"
    model_dtype: "FP16"
    hlora_r: 32
    hlora_alpha: 64
    hlora_dropout: 0
    hlora_nums: 4
    instruct_template: "phi4_instruct"
  default:
    pre_prompt: ""
    post_prompt: ""
  dataset:
