include:
  - ../medvision/lmms_eval_specific_kwargs.yaml
  - ../medvision/metadata.yaml
tag: MedVision-BoxCoordinate,AMOS22
dataset_path: YongchengYAO/MedVision
dataset_kwargs:
  token: True
  trust_remote_code: True
  # download_mode: force_redownload
test_split: test
fewshot_split: test
num_fewshot: 0
output_type: generate_until
doc_to_visual: !function utils.doc_to_visual_wBox
doc_to_text: !function utils.doc_to_text_BoxCoordinate_wBox
doc_to_target: !function utils.doc_to_target_BoxCoordinate
process_results: !function utils.process_results_BoxCoordinate
metric_list:
- metric: avgMAE
  aggregation: !function utils.aggregate_results_avgMAE
  higher_is_better: false
- metric: avgMRE
  aggregation: !function utils.aggregate_results_avgMRE
  higher_is_better: false
- metric: SuccessRate
  aggregation: !function utils.aggregate_results_SuccessRate
  higher_is_better: true
